server:
  port: 8789

spring:
  application:
    name: api-gateway
  profiles:
    active:
      default

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 30 # eureka에게 서비스 정보를 가져오는 주기
    disable-delta: true # eureka에게 서비스 정보를 가져올때 변경된 내용만 가져온다. (false로 하면 전체를 가져오기에 대역폭 낭비이다.)
    serviceUrl:
      defaultZone: http://localhost:8788/eureka/

zuul:
  prefix:  /api #localhost:5555/api/서비스명/ribbon/{}
  routes:
    # 이렇게 임의의 경로를 직접 매핑하면 http://localhost:5555/srve2/v1/로도 요청가능
    service2: /srve2/**

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"